//____________________GET EMPLOYEES AND SERVICES
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_SERVICES = "GET_SERVICES";
//____________________SET EMPLOYEES AND SERVICES
export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const SET_SERVICES = "SET_SERVICES";
//____________________BOOK APPOINTMENT
export const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";
//____________________GET_SPECIALIZATIONS
export const GET_SPECIALIZATIONS = "GET_SPECIALIZATIONS";
//___________________SET_SPECIALIZATIONS
export const SET_SPECIALIZATIONS = "SET_SPECIALIZATIONS";